include:
  - local: 'terraform-runner/.gitlab-ci.yml'

before_script:
  - echo "$SERVICE_ACCOUNT_JSON" | base64 -d > service-account.json
  - gcloud auth activate-service-account "$SERVICE_ACCOUNT_NAME" --key-file=service-account.json
  - gcloud auth print-access-token | crane auth login -u oauth2accesstoken --password-stdin gcr.io 
  - rm -r $CI_PROJECT_DIR/service-account.json

stages:
  - build
  - test
  - deploy

build-job:
  stage: build
  only:
    - develop
  script:
    - cd terraform-runner
    - IMAGE_TAG="$(cat version.txt)"
    - crane manifest exists gcr.io/devops-workshops-2023:${IMAGE_TAG}
    - docker push gcr.io/devops-workshops-2023/terraform-runner:${IMAGE_TAG}

