include:
  - local: 'my_image/.gitlab-ci.yml'

before_script:
  - cd $BUILD_DIR
  - echo "$SERVICE_ACCOUNT_JSON" | base64 -d > service-account.json
  - gcloud auth activate-service-account "$SERVICE_ACCOUNT_NAME" --key-file=service-account.json
  - gcloud auth print-access-token | crane auth login -u oauth2accesstoken --password-stdin gcr.io
  - crane ls $GCR_REGISTRY/staging/$IMAGE_NAME > all_versions.txt
  - cat all_versions.txt | grep -o "$(cat version.txt)" > version_image.txt || true
  - pwd
  - ls
  - cat version_image.txt

stages:
  - check_image_existence
  - build_and_tag_image_master

.check_image_existence:
  stage: check_image_existence
  image: gcr.io/devops-workshop-2023/terraform-runner:0.0.0
  script:
    - >
      if [ ! -s "version_image.txt" ]; then
        IMAGE_TAG="$(cat version.txt)"
        gcloud builds submit --project=devops-workshop-2023 --tag=gcr.io/devops-workshop-2023/staging/$IMAGE_NAME:$IMAGE_TAG-$CI_COMMIT_SHORT_SHA
      else
        echo "Please update version.txt, image with this tag already exists in gcr.io";
        exit 1;
      fi;
  when: manual
  allow_failure: false

.build_and_tag_image_master:
  stage: build_and_tag_image_master
  script:
    - >
      cd $BUILD_DIR
      if [ ! -s "version_image.txt" ]; then
        IMAGE_TAG="$(cat version.txt)"
        gcloud builds submit --project=devops-workshop-2023 --tag=gcr.io/devops-workshop-2023/$IMAGE_NAME:$IMAGE_TAG
      else
        echo "Please update version.txt, image with this tag already exists in gcr.io";
        exit 1;
      fi;
  allow_failure: false




