variables:
  GCR_REGISTRY: gcr.io/devops-workshop-2023/terraform-runner

before_script:
  - echo "$SERVICE_ACCOUNT_JSON" | base64 -d > service-account.json
  - gcloud auth activate-service-account "$SERVICE_ACCOUNT_NAME" --key-file=service-account.json
  - gcloud auth print-access-token | crane auth login -u oauth2accesstoken --password-stdin gcr.io

stages:
  - check_version
  - tag_image

.build_branch_templates:
  stage: check_version
  image: gcr.io/devops-workshop-2023/terraform-runner:0.0.0
  script:
    - crane ls $GCR_REGISTRY/$IMAGE_NAME > all_versions.txt
    - cat all_versions.txt | grep -Fxq "$(cat version.txt)" > version_image.txt || true 
    - VERSION_IMAGE="$(cat version_image.txt)"
    - IMAGE_TAG="$(cat version.txt)"
    - export IMAGE_TAG="$(cat version.txt)"

job1:
  extends: .build_branch_templates
  script:
    - >
      if [ -n "$VERSION_IMAGE" ]; then
        echo "Please update version.txt, image with this tag already exists in gcr.io"; 
      else
        gcloud builds submit --project=devops-workshop-2023 --tag=gcr.io/devops-workshop-2023/staging:$IMAGE_TAG
      fi;

tag_image:
  stage: tag_image
  image: gcr.io/devops-workshop-2023/terraform-runner:0.0.0
  script:
    - echo "Hello World"













