variables:
  IMAGE_NAME: terraform-runner
  GCR_REGISTRY: gcr.io/devops-workshop-2023

stages:
  - build

job1:
  stage: build
  image: gcr.io/devops-workshop-2023/terraform-runner:0.0.0
  script:
  - echo "$SERVICE_ACCOUNT_JSON" | base64 -d > service-account.json
  - gcloud auth activate-service-account "$SERVICE_ACCOUNT_NAME" --key-file=service-account.json
  - gcloud auth print-access-token | crane auth login -u oauth2accesstoken --password-stdin gcr.io 
  - gcloud builds submit --project=devops-workshop-2023 --tag=${GCR_REGISTRY}/${IMAGE_NAME}:1.0.2
     
