include:
  - local: 'terraform-runner/.gitlab-ci.yml'

before_script:
  - echo "$SERVICE_ACCOUNT_JSON" | base64 -d > service-account.json
  - gcloud auth activate-service-account "$SERVICE_ACCOUNT_NAME" --key-file=service-account.json
  - gcloud auth print-access-token | crane auth login -u oauth2accesstoken --password-stdin gcr.io

stages:
  - check_image_existence
  - build_and_tag_image_master

.check_image_existence:
  stage: check_image_existence
  image: gcr.io/devops-workshop-2023/terraform-runner:0.0.0
  script:
    - cd $IMAGE_NAME
    - crane ls $GCR_REGISTRY/$IMAGE_DIR > all_versions.txt
    - cat all_versions.txt | grep -o "$(cat version.txt)" > version_image.txt || true
  after_script:
    - >
      cd $IMAGE_NAME;
      if [ -s "version_image.txt" ]; then
        echo "Please update version.txt, image with this tag already exists in gcr.io"; exit 1;
      else
        IMAGE_TAG="$(cat version.txt)"
        gcloud builds submit --project=devops-workshop-2023 --tag=gcr.io/devops-workshop-2023/staging:$IMAGE_TAG-$CI_COMMIT_SHA
      fi;
  when: manual
  allow_failure: true
  
.build_and_tag_image_master:
  stage: build_and_tag_image_master
  script:
    - >
      if [ -n "$VERSION_IMAGE" ]; then
        echo "Please update version.txt, image with this tag already exists in gcr.io"; 
      else
        cd $IMAGE_NAME
        IMAGE_TAG="$(cat version.txt)"
        gcloud builds submit --project=devops-workshop-2023 --tag=gcr.io/devops-workshop-2023:$IMAGE_TAG
      fi;
  only:
    - master












