include:
  - local: 'terraform-runner/.gitlab-ci.yml'


before_script:
  - echo $SERVICE_ACCOUNT_JSON | base64 -d > $CI_PROJECT_DIR/service-account.json
  - gcloud auth activate-service-account $SERVICE_ACCOUNT_NAME --key-file=$CI_PROJECT_DIR/service-account.json --project=devops-workshop-2023
  - rm -r $CI_PROJECT_DIR/service-account.json
<<<<<<< HEAD
  - SERVICE_ACCOUNT_DECODED=$(echo "$SERVICE_ACCOUNT_JSON" | base64 -d)
  - export SERVICE_ACCOUNT_DECODED
  - echo $SERVICE_ACCOUNT_DECODED | docker login -u "$DOCKER_NAME" --password-stdin $CI_REGISTRY
=======
  - crane auth login
  - echo $GCLOUD_PROJECT_ID > $CI_PROJECT_DIR/gcloud-project-id

stages:
  - build
  - test
  - deploy
>>>>>>> 83d297b (update .gitlab-ci.yml)

build-job:
  stage: build
  only:
    - develop
  script:
    - cd terraform-runner
    - IMAGE_TAG="$(cat version.txt)"
<<<<<<< HEAD
    - crane version
    - SERVICE_ACCOUNT_DECODED=$(echo "$SERVICE_ACCOUNT_JSON" | base64 -d)
    - export SEVICE_ACCOUNT_DECODED
    - echo $SERVICE_ACCOUNT_DECODED | crane auth login -u "$DOCKER_NAME" --password-stdin $CI_REGISTRY

=======
    - crane manifest exists gcr.io/devops-workshops-2023/${CI_COMMIT_SHA}:${image_tag}
    - gcloud builds submit --project=$GCLOUD_PROJECT_ID --tag gcr.io/devops-workshops-2023/terraform-runner:${CI_COMMIT_SHA}
    - cd terraform-runner
    - gcloud containers images add-tag gcr.io/devops-workshops-2023/terraform-runner:${CI_COMMIT_SHA} gcr.io/devops-workshops-2023/terraform-runner:${image_tag}
>>>>>>> 83d297b (update .gitlab-ci.yml)
