include:
  - local: 'terraform-runner/.gitlab-ci.yml'

variables:
  IMAGE_NAME: terraform-runner
  VERSION_TAG: $(cat docker/terraform-runner/version.txt)
  GCR_REGISTRY: gcr.io/devops-workshops-2023

before_script:
  - echo "$SERVICE_ACCOUNT_JSON" | base64 -d > service-account.json
  - gcloud auth activate-service-account "$SERVICE_ACCOUNT_NAME" --key-file=service-account.json
  - gcloud auth print-access-token | crane auth login -u oauth2accesstoken --password-stdin gcr.io 
  - rm -r $CI_PROJECT_DIR/service-account.json
  - gcloud auth configure-docker -y

stages:
  - build

.build_branch_templates:
  stage: build
  image: gcr.io/devops-workshop-2023/terraform-runner:v1.0.1
  only:
    - develop
  script:
    - echo "Checking if image with tag $VERSION_TAG already exists in $GCR_REGISTRY/$IMAGE_NAME:$VERSION_TAG"
    - crane manifest $GCR_REGISTRY/$IMAGE_NAME:$VERSION_TAG
