stages:
  - build
  - test
  - deploy

before_script:
  - echo $SERVICE_ACCOUNT_JSON | base64 -d > $CI_PROJECT_DIR/service-account.json
  - gcloud auth activate-service-account $SERVICE_ACCOUNT_NAME --key-file=$CI_PROJECT_DIR/service-account.json --project=devops-workshop-2023
  - rm -r $CI_PROJECT_DIR/service-account.json
  - SERVICE_ACCOUNT_DECODED=$(echo "$SERVICE_ACCOUNT_JSON" | base64 -d)
  - export SERVICE_ACCOUNT_DECODED
  - echo $SERVICE_ACCOUNT_DECODED | docker login -u "$DOCKER_NAME" --password-stdin $CI_REGISTRY
  - gcloud auth list

build-job:
  stage: build
  only:
    refs:
      - develop
  image:
    name: gcr.io/devops-workshop-2023/terraform-runner:1.0.1
  script:
    - cd terraform-runner
    - IMAGE_TAG="$(cat version.txt)"
    - crane version
    - SERVICE_ACCOUNT_DECODED=$(echo "$SERVICE_ACCOUNT_JSON" | base64 -d)
    - echo $SERVICE_ACCOUNT_DECODED | crane auth login -u "$DOCKER_NAME" --password-stdin $CI_REGISTRY

