include:
  - local: '/terraform-runner/.gitlab-ci.yml'

variables:
  IMAGE_NAME: terraform-runner
  GCR_REGISTRY: gcr.io/devops-workshops-2023

before_script:
  - echo "$SERVICE_ACCOUNT_JSON" | base64 -d > service-account.json
  - gcloud auth activate-service-account "$SERVICE_ACCOUNT_NAME" --key-file=service-account.json
  - gcloud auth print-access-token | crane auth login -u oauth2accesstoken --password-stdin gcr.io 
 
stages:
  - check_version
  - build
  - tag_image

.build_branch_templates:
  stage: check_version
  image: gcr.io/devops-workshop-2023/terraform-runner:v1.0.1
  only:
    - develop
  script:
    - IMAGE_TAG=$(cat version.txt)"
    - crane ls $GCR_REGISTRY/$IMAGE_NAME > all_versions.txt
    - |
    - if cat all_versions.txt | grep -q "$IMAGE_TAG"; then
        echo "Please update version.txt, image with this tag already exists in $GCR_REGISTRY"
        exit 1
      else
        echo "Build"
      fi
