stages:
  - 1.0.1

docker-tag-1.0.1:
  stage: 1.0.1
  only:
    refs:
      - master
  image:
    name: gcr.io/devops-workshop-2023/terraform-runner@sha256:02e3336558cad226f9aef0a0674dedeec0d65ced26cdf2c97703fb1959617429
    entrypoint: [""]
  script:
    - cd image_dir
    - IMAGE_TAG=$(cat version.txt)
    - crane version
    - crane auth login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - crane tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA 1.0.1
