variables:
  IMAGE_NAME: terraform-runner
  GCR_REGISTRY: gcr.io/devops-workshop-2023

before_script:
  - echo "$SERVICE_ACCOUNT_JSON" | base64 -d > service-account.json
  - gcloud auth activate-service-account "$SERVICE_ACCOUNT_NAME" --key-file=service-account.json
  - gcloud auth print-access-token | crane auth login -u oauth2accesstoken --password-stdin gcr.io

stages:
  - check_version
  - build
  - tag_image

build_branch_templates:
  stage: check_version
  image: gcr.io/devops-workshop-2023/terraform-runner:0.0.0
  script:
    - crane ls $GCR_REGISTRY/$IMAGE_NAME > all_versions.txt
    - ALL_VERSIONS="$(cat all_versions.txt)"
    - echo "$ALL_VERSIONS"
    - (grep -Fxq "$(cat version.txt)" all_versions.txt && echo "$(cat version.txt)") > version_image.txt
    - IMAGE_TAG="$(cat version.txt)"
    - VERSION_IMAGE="$(cat version_image.txt)"
    - ALL_VERSIONS="$(cat all_versions.txt)"
    - echo "$(cat version.txt)"
    - echo "$(cat version_image.txt)"
    - echo "$(cat all_versions.txt)"
