variables:
  GCR_REGISTRY: gcr.io/devops-workshop-2023
  IMAGE_NAME: staging

check_image_existence:
  extends: .check_image_existence

build_and_tag_image:
  extends: .build_and_tag_image

build_and_tag_image_master:
  extends: build_and_tag_image_master
