extends: ../.build_branch_template.yml

stages:
  - build

build:
  stage: build
  image: my_custom_image:latest 
  script:
    - cd terraform-runner
    - IMAGE_TAG="$(cat version.txt)"
    - crane manifest exists gcr.io/devops-workshops-2023:${IMAGE_TAG}
    - docker push gcr.io/devops-workshops-2023/terraform-runner:${IMAGE_TAG}

