before_script:
  - cd terraform-runner
  - IMAGE_TAG="$(cat version.txt)"

stages:
  - build

build:
  stage: build
  script:
    - docker build -t my_image:1.0.1 .
    - crane manifest exists gcr.io/devops-workshops-2023:${IMAGE_TAG}
    - docker push gcr.io/devops-workshops-2023/terraform-runner:${IMAGE_TAG}

