variables:
  GCR_REGISTRY: gcr.io/devops-workshop-2023
  BUILD_DIR: terraform-runner 
  IMAGE_NAME: my_image  

check_image_existence:
  extends: .check_image_existence

build_and_tag_image_master:
  extends: .build_and_tag_image_master
